<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer
 * @var $escaper Magento\Framework\Escaper
 */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item product-item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
            <div class="amtheme-inner">
                <?php if ($block->hasProductUrl()) :?>
                <a href="#"
                   title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
                    <?php else :?>
                    <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <?php if ($block->hasProductUrl()) :?>
                            <a href="#"><?= $block->escapeHtml($block->getProductName()) ?></a>
                        <?php else :?>
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </strong>
                    <?php if ($_options = $block->getOptionList()) :?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option) :?>
                                <?php if($block->escapeHtml($_option['label']) !== 'Value' && $block->escapeHtml($_option['label']) !== 'Delivery Date' && $block->escapeHtml($_option['label']) !== 'Image'): ?>
                                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                    <dd>
                                        <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                            <?php if (strpos($_formatedOptionValue['full_view'], 'bss-gc-img') !== false) :?>
                                                <?= $_formatedOptionValue['full_view'] ?>
                                            <?php else :?>
                                                <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                            <?php endif; ?>
                                        <?php else :?>
                                            <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                        <?php endif; ?>
                                    </dd>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif;?>
<!--                    --><?php //if ($messages = $block->getMessages()) :?>
<!--                        --><?php //foreach ($messages as $message) :?>
<!--                            <div class= "cart item message  $block->escapeHtmlAttr($message['type']) ">-->
<!--                                <div> $block->escapeHtml($message['text']) </div>-->
<!--                            </div>-->
<!--                        --><?php //endforeach; ?>
<!--                    --><?php //endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock) :?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif;?>
                </div>
            </div>
        </td>

        <?php if ($canApplyMsrp) :?>
            <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
            <div class="field qty amtheme-qty-wrap -square">
                <div class="control amtheme-qty-box" data-mage-init='{"amQty":{}}'>
                    <div class="control amtheme-qty-box">
                        <div class="amtheme-minus" data-amtheme-js="qty-minus" tabindex="0" title="Minus">
                            <svg class="amtheme-icon">
                                <use xlink:href="#icon-minus"></use>
                            </svg>
                        </div>
                        <div class="amtheme-plus" data-amtheme-js="qty-plus" tabindex="0" title="Plus">
                            <svg class="amtheme-icon">
                                <use xlink:href="#icon-plus"></use>
                            </svg>
                        </div>
                        <input id="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $escaper->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty amtheme-qty"
                               tabindex="0"
                               data-amtheme-js="qty-input"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                    </div>
                </div>
            </div>
        </td>

        <td class="col subtotal amtheme-column-toolbar">
            <div class="amtheme-cell">
                <div class="subtotal">
                    <span class="amtheme-label-small"><?= $escaper->escapeHtml(__('Subtotal')) ?></span>
                    <?php if ($canApplyMsrp): ?>
                        <span class="cart msrp subtotal">--</span>
                    <?php else: ?>
                        <?= $block->getRowTotalHtml($_item) ?>
                    <?php endif; ?>
                </div>
            </div>
        </td>
    </tr>
    <tr class="item-actions">
        <td class="col item" colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
<style>
    .gift-card-actions .action-edit {
        border-right: 1px solid #565656;
        padding: 0 15px 0 0;
        color: #03cf62;

        font-size: 1.2rem;
        font-weight: 700;
        letter-spacing: 0.06em;
        text-transform: uppercase;
        margin: 0 0 0 20px;
        order: 1;
    }
    .gift-card-actions .action-delete {
        border-right: unset;
        padding: 0;
        color: #03cf62 !important;
        font-size: 1.2rem;
        font-weight: 700;
        letter-spacing: 0.06em;
        text-transform: uppercase;
        margin: 0 0 0 20px;
        order: 1;
    }
</style>
