<?php

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');

if($request->getModuleName() == "einvoicemanagement"){ ?>
  <style type="text/css">
  .import_wrap {
  border: 1px solid #dedede;
  width: 100%;
  float: left;
  padding: 50px;
}
.import_left, .import_right {
  width: 50%;
  float: left;
  text-align: center;
}
#files {
  width: 300px;
  margin: auto;
}

.autocomplete-items div {
  width: 300px;
  text-align: left;
  margin: auto;
  cursor: pointer;
  padding: 1px 5px;
}
.autocomplete-items div:hover {
  background: #196d39; 
  color: #fff;
}
#myInput{ width: 300px;height: 34px;font-size: 16px; }
.autocomplete{ width:100%; }
.cwsFiles{ display:none; }
.sticky-header{ top: 0 !important }
</style>
<script type="text/javascript">
  var countries = [];
  var countries2 = [];
  var countries3 = [];
  var countries4 = [];
</script>

    <select id="files" name="file_customer" class="option-control cwsFiles">
      <option value=""><?php echo __("Please Select a customer"); ?></option>
    <?php
      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      $customerObj = $objectManager->create('Os\EinvoiceManagement\Model\InvoiceFactory')->create()->getCollection();
      $list_cu = array();
      $list_cu2 = array();
      $list_cu3 = array();
      $list_cu4 = array();
      foreach($customerObj as $customerObjdata )
      { ?>

    <?php
          $textforthis = str_replace('"', '', $customerObjdata->getData('BUYER_NAME'));
          $textforthis = str_replace("'", "", $textforthis);
          if(in_array($textforthis, $list_cu)){

          } else {

            $list_cu[] = $textforthis;
        ?>
        <script type="text/javascript">
          countries['canhtn<?php echo $customerObjdata->getId() ?>'] = "<?php echo $textforthis ?>";
        </script>
        
    <?php } ?>

    <?php
          $textforthis = str_replace('"', '', $customerObjdata->getData('OPERATING_UNITS'));
          $textforthis = str_replace("'", "", $textforthis);
          if(in_array($textforthis, $list_cu2)){

          } else {

            $list_cu2[] = $textforthis;
        ?>
        <script type="text/javascript">
          countries2['canhtn<?php echo $customerObjdata->getId() ?>'] = "<?php echo $textforthis ?>";
        </script>
        
    <?php } ?>

    <?php
          $textforthis = str_replace('"', '', $customerObjdata->getData('BRANCH_NAME'));
          $textforthis = str_replace("'", "", $textforthis);
          if(in_array($textforthis, $list_cu3)){

          } else {

            $list_cu3[] = $textforthis;
        ?>
        <script type="text/javascript">
          countries3['canhtn<?php echo $customerObjdata->getId() ?>'] = "<?php echo $textforthis ?>";
        </script>
        
    <?php } ?>

    <?php
          $textforthis = str_replace('"', '', $customerObjdata->getData('INVOICE_CLASS'));
          $textforthis = str_replace("'", "", $textforthis);
          if(in_array($textforthis, $list_cu4)){

          } else {

            $list_cu4[] = $textforthis;
        ?>
        <script type="text/javascript">
          countries4['canhtn<?php echo $customerObjdata->getId() ?>'] = "<?php echo $textforthis ?>";
        </script>
        
    <?php } ?>
    <?php } ?>
    </select>


<?php } ?>