<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_JetTheme
 */
?>
<?php $_product = $block->getProduct(); ?>

<?php if ($_product->isSaleable() && $block->hasOptions()) : ?>
    <div class="bundle-summary">
        <?= $block->getChildHtml('', true) ?>
        <strong class="subtitle"><?php /* @escapeNotVerified */ echo __('Summary'); ?></strong>
        <div id="bundle-summary" data-container="product-summary">
            <ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
            <script data-template="bundle-summary" type="text/x-magento-template">
                <li>
                        <strong class="label"><%- data._label_ %>:</strong>
                        <div data-container="options"></div>
                    </li>
                </script>
            <script data-template="bundle-option" type="text/x-magento-template">
                <div><?php /* @escapeNotVerified */ echo __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?></div>
                </script>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            ".product-add-form": {
                "amBundleVisibility": {
                    <?php if ($block->isStartCustomization()) : ?>
                    "autostart": true
                    <?php endif; ?>
                }
            }
        }
    </script>
<?php endif; ?>