<?php
    $approveds = $this->getApprovedDefaultCollection();

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    
    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<style type="text/css">
 .page-main > .page-title-wrapper .page-title {
    display: none;
}
.page-wrapper > .breadcrumbs{ max-width: 100%; }
.col2-left-layout .col-left.sidebar {
    padding-right: 12px;
    align-self: flex-start;
}
.sidebar .left_my_account {
    background: #000 none repeat scroll 0 0;
    padding: 20px;
    text-align: center;
}
.sidebar .left_my_account p.icon {
    margin-bottom: 20px;
}
.sidebar .left_my_account p.name {
    font-weight: 600;
}
.sidebar .left_my_account p {
    color: #ffffff;
    margin: 0;
}
.sidebar .block-account .block-content {
    background: rgba(0, 0, 0, 0) linear-gradient(to right, #196d39, #dff0d8) repeat scroll 0 0;
    padding-top: 20px;
}
.block-account ul li, .block.block-blog-categories .blog-category {
    padding: 8px 3px 8px 18px;
    position: relative;
    line-height: 1.3;
    border-bottom: 1px solid #ddd;
        border-bottom-color: rgb(221, 221, 221);
}
.sidebar .block-account .block-content li {
    border-color: #c99597;
    margin: 0 20px;
    padding: 5px 0;
}
.fa {
    display: inline-block;
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.sidebar .left_my_account .icon span {
    background: #afafc3 none repeat scroll 0 0;
    border: 2px solid #6b6db6;
    border-radius: 50%;
    display: inline-block;
    font-size: 42px;
    height: 65px;
    line-height: 60px;
    width: 65px;
}
.sidebar .block-account .block-content li a, .sidebar .block-account .block-content li strong {
    color: #ffffff;
    display: block;
    line-height: 29px;
    padding: 2px 0 2px 15px;
}
.block-account ul li, .block.block-blog-categories .blog-category {
    line-height: 1.3;
}
.sidebar .block-account .block-content li:last-child {
    border-bottom: 0 none;
}
</style>
<div class="col-left sidebar f-left col-lg-3" style="width:22.3% !important;float:left !important;padding: 0 22px 0 0 !important;">
    <div class="block block-account">
        <div class="left_my_account">
            <p class="icon"><span><i class="fa fa-user" aria-hidden="true"></i></span></p>
            <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerSession = $objectManager->create('Magento\Customer\Model\Session'); 
            ?>
            <p class="name"><?php echo $customerSession->getCustomer()->getName();  ?></p>
            <p class="email"><?php echo $customerSession->getCustomer()->getEmail(); ?></p>
        </div>
        
        <div class="block-content">
            <ul style="padding: 0;list-style: none;">
                <li><a href="<?php echo $this->getBaseUrl() ?>customer/account/">Account Dashboard</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>customer/account/edit/">Account Information</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>sales/order/history/">My Orders</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>emailorder/invoice/list/">My Invoices</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>daily-on-hand-stock/">Daily On-Hand Stock</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>suggested-order/">Suggested Order</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>approved-release-confirmation/">Approved Releases</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>receipt-confirmation/">Receipt Confirmation</a></li>
<li><a href="<?php echo $this->getBaseUrl() ?>customer-statement/">Customer Statement</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>emailorder/index/list/">Notifications</a></li>
                <li class="last"><a href="<?php echo $this->getBaseUrl() ?>customer/account/subAccount/">Manage Users</a></li>
            </ul>
        </div>
    </div>
</div>
<div style="width: 77.7%;float: left;">
<div class="os-custom-order">
    <div class="page-title">
            <h1 style="font-size: 20px;margin: 0 0 15px;color: #196d39;text-transform: uppercase;font-weight: 600; ">APPROVED RELEASES</h1>
        </div>
    <div class="filter">
        <div class="filter-date" style="width: 50%;float: left;color: #777;">
            <table>
                <tbody>
                    <tr>
                        <td><label for="from-date"><?= __('From Date') ?></label></td>
                        <td>
                            <input name="datepicker-fromdate" id="datepicker-fromdate" type="text" autocomplete="off">
                        </td>
                    </tr>
                    <tr>
                        <td><label for="to-date"><?= __('To Date') ?></label></td>
                        <td>
                            <input name="datepicker-todate" id="datepicker-todate" type="text" autocomplete="off">
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="filter-request" style="width: 50%;float: left;color: #777;">
            <table>
                <tbody>
                    <tr>
                        <td><label for="release"><?= __('Release #') ?></label></td>
                        <td>
                            <input name="release" id="filter_release" type="text">
                        </td>
                    </tr>
                    <tr>
                        <td><label for="request"><?= __('Request #') ?></label></td>
                        <td>
                            <input name="request" id="filter_request" type="text">
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="table-item">
        <div class="table_field">
            <table border="1" cellpadding="5" style="border-color: #dcdcdc;" cellspacing="5">
                <thead>
					<tr>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;">Date</th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;">Request ID</th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;">Release #</th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;">Total</th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;"></th>
					</tr>
                </thead>
                <tbody>
                    <?php if (count($approveds) > 0) : ?>
                        <?php foreach ($approveds as $approved) : ?>
                            <?php
								$currentDate = date($approved->getData('DATE'));
								$dateToStr = strtotime($currentDate);
								$newDate = date("m/d/Y H:i:s", $dateToStr);
                            ?>
                            <tr>
								<td style="border-color: #dcdcdc;"><?= $newDate ?></td>
								<td style="border-color: #dcdcdc;"><?= $approved->getData('REQUEST_ID') ?></td>
								<td style="border-color: #dcdcdc;"><?= $approved->getData('RELEASE_NUMBER') ?></td>
								<td style="border-color: #dcdcdc;"><?= $priceHelper->currency($approved->getData('TOTAL'), true, false); ?></td>
								<td style="border-color: #dcdcdc;">
									<a href="<?= $block->getUrl('dsfhcustomer/approved/detail')."release/".$approved->getData('RELEASE_NUMBER') ?>">
										View
									</a>
								</td>
							</tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    require(["jquery", "mage/calendar"], function ($) {

        
        $('#datepicker-fromdate, #datepicker-todate').calendar({
            // show date
            changeYear: true,
            changeMonth: true,
            yearRange: '1970:2050',
            buttonText: 'Select Date',
            // show time as well
            dateFormat: 'dd/mm/yyyy',
            timeInput: false,
            timeFormat: 'mm:HH:ss',
            showsTime: false
        });

        $('#datepicker-fromdate, #datepicker-todate, #filter_release, #filter_request').change(function(event) {

            var inputFromDate = $('#datepicker-fromdate').val();
            var inputToDate = $('#datepicker-todate').val();
            var inputRelease = $('#filter_release').val();
            var inputRequest = $('#filter_request').val();

            if (checkDate(inputFromDate) && checkDate(inputToDate)) {
                $.ajax({
                    url: '<?php echo $block->getUrl('dsfhcustomer/filter/approved') ?>',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        from_date: inputFromDate,
                        to_date: inputToDate,
                        release: inputRelease,
                        request: inputRequest
                    },
                    success : function (result){

                        if (result.data.count_data == 0) {
                            alert("There is no data for this date");
                            $('.os-custom-order .table_field table tbody').html("");
                        } else {
                            $('.os-custom-order .table_field table tbody').html(result.data.content);
                        }
                    }
                });
            }
        });

        function checkDate(field)
        {
            var allowBlank = true;
            var minYear = 1902;
            var maxYear = (new Date()).getFullYear();
            var errorMsg = "";
            re = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/;

            if (field != '') {
                if (regs = field.match(re)) {
                    if (regs[1] < 1 || regs[1] > 31) {
                    errorMsg = "Invalid value for day: " + regs[1];
                    } else if (regs[2] < 1 || regs[2] > 12) {
                    errorMsg = "Invalid value for month: " + regs[2];
                    } else if (regs[3] < minYear || regs[3] > maxYear) {
                    errorMsg = "Invalid value for year: " + regs[3] + " - must be between " + minYear + " and " + maxYear;
                    }
                } else {
                    errorMsg = "Invalid date format: " + field;
                }
            } else if (!allowBlank) {
                errorMsg = "Empty date not allowed!";
            }

            if (errorMsg != "") {
                alert(errorMsg);
                return false;
            }

            return true;
        }
    });
</script>
</div>