<?php
    $suggesteds = $block->getSuggestedCollection();

    $fromDate = "1970-01-01 00:00:00";
    $toDate = date('2025-01-01 23:59:59');
    $suggesteds->getSelect()->columns(['TOTAL' => new \Zend_Db_Expr('SUM(UNIT_PRICE*QTY)')])
            ->group('REQUEST_ID')
            ->order('TRX_DATE DESC');
    
    $suggesteds->addFieldToFilter('TRX_DATE', array(
        'from' => $fromDate,
        'to' => $toDate,
        'date' => true,
    ));

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<style type="text/css">
    .page-main > .page-title-wrapper .page-title {
    display: none;
}
.page-wrapper > .breadcrumbs{ max-width: 100%; }
.col2-left-layout .col-left.sidebar {
    padding-right: 12px;
    align-self: flex-start;
}
.sidebar .left_my_account {
    background: #000 none repeat scroll 0 0;
    padding: 20px;
    text-align: center;
}
.sidebar .left_my_account p.icon {
    margin-bottom: 20px;
}
.sidebar .left_my_account p.name {
    font-weight: 600;
}
.sidebar .left_my_account p {
    color: #ffffff;
    margin: 0;
}
.sidebar .block-account .block-content {
    background: rgba(0, 0, 0, 0) linear-gradient(to right, #196d39, #dff0d8) repeat scroll 0 0;
    padding-top: 20px;
}
.block-account ul li, .block.block-blog-categories .blog-category {
    padding: 8px 3px 8px 18px;
    position: relative;
    line-height: 1.3;
    border-bottom: 1px solid #ddd;
        border-bottom-color: rgb(221, 221, 221);
}
.sidebar .block-account .block-content li {
    border-color: #c99597;
    margin: 0 20px;
    padding: 5px 0;
}
.fa {
    display: inline-block;
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.sidebar .left_my_account .icon span {
    background: #afafc3 none repeat scroll 0 0;
    border: 2px solid #6b6db6;
    border-radius: 50%;
    display: inline-block;
    font-size: 42px;
    height: 65px;
    line-height: 60px;
    width: 65px;
}
.sidebar .block-account .block-content li a, .sidebar .block-account .block-content li strong {
    color: #ffffff;
    display: block;
    line-height: 29px;
    padding: 2px 0 2px 15px;
}
.block-account ul li, .block.block-blog-categories .blog-category {
    line-height: 1.3;
}
.sidebar .block-account .block-content li:last-child {
    border-bottom: 0 none;
}
</style>
<div class="col-left sidebar f-left col-lg-3" style="width:22.3% !important;float:left !important;padding: 0 22px 0 0 !important;">
    <div class="block block-account">
        <div class="left_my_account">
            <p class="icon"><span><i class="fa fa-user" aria-hidden="true"></i></span></p>
            <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerSession = $objectManager->create('Magento\Customer\Model\Session'); 
            ?>
            <p class="name"><?php echo $customerSession->getCustomer()->getName();  ?></p>
            <p class="email"><?php echo $customerSession->getCustomer()->getEmail(); ?></p>
        </div>
        
        <div class="block-content">
            <ul style="padding: 0;list-style: none;">
                <li><a href="<?php echo $this->getBaseUrl() ?>customer/account/">Account Dashboard</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>customer/account/edit/">Account Information</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>sales/order/history/">My Orders</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>emailorder/invoice/list/">My Invoices</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>daily-on-hand-stock/">Daily On-Hand Stock</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>suggested-order/">Suggested Order</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>approved-release-confirmation/">Approved Releases</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>receipt-confirmation/">Receipt Confirmation</a></li>
<li><a href="<?php echo $this->getBaseUrl() ?>customer-statement/">Customer Statement</a></li>
                <li><a href="<?php echo $this->getBaseUrl() ?>notifications/">Notifications</a></li>
                <li class="last"><a href="<?php echo $this->getBaseUrl() ?>customer/account/subAccount/">Manage Users</a></li>
            </ul>
        </div>
    </div>
</div>
<div style="width: 77.7%;float: left;">
<div class="os-custom-order">
    <div class="page-title">
            <h1 style="font-size: 20px;margin: 0 0 15px;color: #196d39;text-transform: uppercase;font-weight: 600; ">SUGGESTED ORDER 

</h1>
        </div>
	<div class="filter">
		<div class="filter-date" style="width:50%;float:left;">
			<table>
				<tbody>
					<tr>
						<td><label for="from-date"><?= __('From Date') ?></label></td>
						<td>
                            <input name="datepicker-fromdate" id="datepicker-fromdate" type="text"> 
					    </td>
					</tr>
					<tr>
						<td><label for="to-date"><?= __('To Date') ?></label></td>
						<td>
                            <input name="datepicker-todate" id="datepicker-todate" type="text">
					    </td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="filter-request" style="width:50%;float:left;">
			<table>
				<tbody>
					<tr>
						<td><label for="request"><?= __('Suggested Order Number #') ?></label></td>
						<td>
                            <input name="request" id="filter_request" type="text">
					    </td>
					</tr>
                    <tr>
                        <td><label for="request"><?= __('Product Name #') ?></label></td>
                        <td>
                            <input name="request_productname" id="filter_request_productname" type="text">
                        </td>
                    </tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="table-item">
		<div class="table_field">
			<table border="1" style="border-color: #dcdcdc;" cellpadding="5" cellspacing="5">
				<thead>
					<tr>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;"><?= __('Date') ?></th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;"><?= __('Suggested Order Number') ?>#</th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;"><?= __('Total') ?></th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;"><?= __('Status') ?></th>
						<th style="background: #f6f6f6;color: #777;padding: 10px 5px;border: 1px solid #f6f6f6;font-weight: 600;font-size: 12px;text-align: center;"></th>
					</tr>
				</thead>
				<tbody>
					<?php if (count($suggesteds) > 0) : ?>
						<?php foreach ($suggesteds as $suggested) : ?>
							<?php
								$newDate = date("d/m/Y", strtotime($suggested->getData('TRX_DATE')));
							?>
							<tr>
								<td style="border-color: #dcdcdc;"><?= $newDate ?></td>
								<td style="border-color: #dcdcdc;"><?= $suggested->getData('REQUEST_ID') ?></td>
								<td style="border-color: #dcdcdc;"><?= $priceHelper->currency($suggested->getData('TOTAL'), true, false); ?></td>
								<td style="border-color: #dcdcdc;"><?php if($suggested->getData('CONVERTED_TO_SALES_ORDER') == '1'){?><span class="fa fa-check-circle"></span><?php }else{ ?><span class="fa fa-times-circle"></span><?php } ?></td>
								<td style="border-color: #dcdcdc;">
									<a href="<?= $block->getUrl('dsfhcustomer/suggested/detail')."request/".$suggested->getData('REQUEST_ID') ?>">
                                    <?= __('View') ?>
									</a>

									<?php 
									if($suggested->getData('CONVERTED_TO_SALES_ORDER') <> '1'){ ?>
									<a href="<?= $block->getUrl('/')."?suggested_order=".$suggested->getData('REQUEST_ID')."&org_id=".$suggested->getData('ORG_ID') ?>">
										/ Convert to sales order
									</a>
									<?php } ?>
									
								</td>
							</tr>
						<?php endforeach; ?>
					<?php endif; ?>
				</tbody>
			</table>
		</div>	
	</div>
</div>
<script type="text/javascript">
    require(["jquery", "mage/calendar"], function ($) {
        
        $('#datepicker-fromdate, #datepicker-todate').calendar({
            // show date
            changeYear: true,
            changeMonth: true,
            yearRange: '1970:2050',
            buttonText: 'Select Date',
            // show time as well
            dateFormat: 'mm/dd/yyyy',
            timeInput: false,
            timeFormat: 'mm:HH:ss',
            showsTime: false
        });

        $('#datepicker-fromdate, #datepicker-todate, #filter_request, #filter_request_productname').change(function(event) {

            var inputFromDate = $('#datepicker-fromdate').val();
            var inputToDate = $('#datepicker-todate').val();
            var inputRequest = $('#filter_request').val();
            var inputProductname = $('#filter_request_productname').val();

            if (checkDate(inputFromDate) && checkDate(inputToDate)) {
                $.ajax({
                    url: '<?php echo $block->getUrl('dsfhcustomer/filter/suggested') ?>',
                    type: 'POST',
                    dataType: 'json',
                    data: { 
                        from_date: inputFromDate,
                        to_date: inputToDate,
                        name: inputProductname,
                        request: inputRequest
                    },
                    success : function (result){
                        
                        if (result.data.count_data == 0) {
                            alert("There is no data for this date");
                            $('.os-custom-order .table_field table tbody').html("");
                        } else {
                            $('.os-custom-order .table_field table tbody').html(result.data.content);
                        }

                    }
                });
            }
        });

        function checkDate(field)
        {
            var allowBlank = true;
            var minYear = 1902;
            var maxYear = (new Date()).getFullYear();
            var errorMsg = "";
            re = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/;

            if (field != '') {
                if (regs = field.match(re)) {
                    if (regs[2] < 1 || regs[2] > 31) {
                    errorMsg = "Invalid value for day: " + regs[1];
                    } else if (regs[1] < 1 || regs[1] > 12) {
                    errorMsg = "Invalid value for month: " + regs[2];
                    } else if (regs[3] < minYear || regs[3] > maxYear) {
                    errorMsg = "Invalid value for year: " + regs[3] + " - must be between " + minYear + " and " + maxYear;
                    }
                } else {
                    errorMsg = "Invalid date format: " + field;
                }
            } else if (!allowBlank) {
                errorMsg = "Empty date not allowed!";
            }

            if (errorMsg != "") {
                alert(errorMsg);
                return false;
            }

            return true;
        }
    });
</script>
</div>