<a class="help-icon am-no-display-mobile" href="/contact">
    <svg viewBox="0 0 32 32" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><g fill="none" stroke="#ffffff" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" class="stroke-000000"><path d="M7 25H6a5 5 0 0 1 0-10h1v10zM26 25h-1V15h1a5 5 0 0 1 0 10zM5 15v-3C5 5.925 9.925 1 16 1s11 4.925 11 11v3M27 25v4a2 2 0 0 1-2 2h-3M18 31h2"></path></g></svg>
    <label><?= $block->escapeHtml(__('Help')); ?></label>
</a>

<style>
    .help-icon:hover,
    .help-icon:focus {
        filter: invert(55%) sepia(99%) saturate(487%) hue-rotate(98deg) brightness(91%) contrast(98%);
    }
</style>
