<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_JetTheme
 */
?>
<span data-action="toggle-nav" class="amtheme-navigation-icon" aria-label="<?= $block->escapeHtml(__('Toggle Nav')) ?>">
    <span class="amtheme-icon-box">
        <span class="amtheme-item -top"></span>
        <span class="amtheme-item -bottom"></span>
        <label><?= $block->escapeHtml(__('Menu')); ?></label>
    </span>
</span>
