<?php
/**
 * @var $block Magento\Checkout\Block\Cart\Item\Renderer
 * @var $helper Magento\Msrp\Helper\Data
 * @var $viewModel Amasty\JetTheme\ViewModel\Checkout\CartViewModel
 * @var $escaper Magento\Framework\Escaper
 */

$APP_BUILDER_URL = $_ENV['BUILDER_EDIT_URL'];
$BUILDER_SKU_ID = $_ENV['BUILDER_SKU_ID'];

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

//            print_r('===debug===');
//            var_dump('<pre>',$block->getProductForThumbnail());
//            print_r('===end===');
//die;
$isBuildYourOwn = in_array($product['sku'], $BUILDER_SKU_ID);
$options = $block->getOptionList();
$previewImgPath = '';
if ($isBuildYourOwn)
{
    foreach ($options as $option)
    {
        if ($option['label'] === 'Preview Image')
        {
//            print_r('===debug===');
//            var_dump('<pre>',json_decode($option['value_id'])->quote_path);
//            print_r('===end===');
            $previewImgPath = '/media/'. json_decode($option['value_id'])->quote_path;
            //$block->getCheckoutSession()->setPreviewImg($previewImgPath);
            break;
        }
    }
}

// phpcs:ignore
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$maskedId = $block->getCheckoutSession()->getMaskedId();
$viewModel = $block->getParentBlock()->getAmViewModel();
$needToShowRegularPrice = false;
if ($viewModel
    && $viewModel->isShowSpecialPriceOnCartPage()
    && !in_array($item->getProductType(), ['bundle'])
    && $viewModel->hasSpecialPrice($item)) {
    $needToShowRegularPrice = true;
    $regularPrice = $product->getPrice();
}
$typeClass = in_array($item->getProductType(), ['bundle']) ? '-bundle' : '';
$qtyType = $viewModel ? $viewModel->getQuantitySelectorType() : 'round';

// phpcs:ignore
$taxHelper = $this->helper(\Magento\Tax\Helper\Data::class);
$allTaxesDisplayEnabled = $taxHelper->displayBothPrices();
$taxClass = $allTaxesDisplayEnabled ? 'tax-included' : '';

?>
<tbody class="cart item product-item">
    <tr class="item-info">
        <td class="col item" data-th="<?= $escaper->escapeHtmlAttr(__('Item')) ?>">
            <div class="amtheme-inner">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="#"
                       title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
                       tabindex="-1"
                       class="product-item-photo">
                <?php else: ?>
                    <span class="product-item-photo">
                <?php endif; ?>
                    <?php if($isBuildYourOwn): ?>
                        <span class="product-image-container" style="width:150px;">
                            <span class="product-image-wrapper" style="padding-bottom: 100%;">
                                <img class="product-image-photo" src="<?= $previewImgPath ?>">
                            </span>
                        </span>
                    <?php else:?>
                        <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                    <?php endif;?>
                <?php if ($block->hasProductUrl()): ?>
                    </a>
                <?php else: ?>
                    </span>
                <?php endif; ?>

                <div class="product-item-details">
                    <span class="product-item-name">
                        <?php if ($block->hasProductUrl()): ?>
                            <a href="#"
                               title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
                               aria-label="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>">
                                <?= $escaper->escapeHtml($block->getProductName()) ?>
                            </a>
                        <?php else: ?>
                            <?= /** @noEscape  */$escaper->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </span>

                    <?php if ($canApplyMsrp): ?>
                        <div class="msrp pricing">
                            <span class="msrp notice">
                                <?= $escaper->escapeHtml(__('See price before order confirmation.')) ?>
                            </span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
                            <a href="#"
                               class="action help map"
                               title="<?= $escaper->escapeHtmlAttr(__("What's this?")) ?>"
                               aria-label="<?= $escaper->escapeHtmlAttr(__("What's this?")) ?>"
                               id="<?= ($escaper->escapeHtmlAttr($helpLinkId)) ?>"
                               data-mage-init='{"addToCart":{
                                        "helpLinkId": "#<?= $escaper->escapeJs($escaper->escapeHtml($helpLinkId)) ?>",
                                        "productName": "<?= $escaper->escapeJs($escaper->escapeHtml($product->getName())) ?>",
                                        "showAddToCart": false
                                    }
                                }'>
                                <?= $escaper->escapeHtml(__("What's this?")) ?>
                            </a>
                        </div>
                    <?php else: ?>
                        <div class="price <?= $needToShowRegularPrice ? ' product-info-price': ''?> <?= /* @noEscape */ $taxClass ?>">
                            <?php if ($needToShowRegularPrice): ?>
                                <div class="special-price">
                                    <?= $block->getUnitPriceHtml($item) ?>
                                </div>
                                <div class="old-price">
                                    <?= /** @noEscape  */ $block->convertPrice($regularPrice, true); ?>
                                </div>
                            <?php else: ?>
                                <?= $block->getUnitPriceHtml($item) ?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (count($options) > 0) : ?>
                        <div class="item-options <?= $escaper->escapeHtmlAttr($typeClass) ?>" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
                            <span data-role="title" class="toggle"><?= $escaper->escapeHtmlAttr(_('See Details')) ?></span>
                            <div data-role="content" class="content" style="display: none;">
                                <ul class="amtheme-product-options <?= $escaper->escapeHtmlAttr($typeClass) ?>">
                                    <?php foreach ($options as $option) : ?>
                                        <?php if ($option['label'] !== 'Preview Image' && $option['label'] !== 'Logo Image'):?>
                                            <li class="amtheme-item">
                                                <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                                <span class="amtheme-title"><?= $escaper->escapeHtml($option['label']) ?></span>
                                                <span class="amtheme-value">
                                                <?php if (isset($formatedOptionValue['full_view'])) : ?>
                                                    <?= $escaper->escapeHtml($formatedOptionValue['full_view']) ?>
                                                <?php else : ?>
                                                    <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                                                <?php endif; ?>
                                            </span>
                                            </li>
                                        <?php endif;?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                                <span><?= $escaper->escapeHtml($message['text']) ?></span>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($item)->toHtml() ?>
                    <?php endif;?>
                </div>
            </div>
        </td>
        <td class="col qty" data-th="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>">
            <div class="field qty amtheme-qty-wrap <?= '-' . $escaper->escapeHtmlAttr($qtyType) ?>">
                <div class="control amtheme-qty-box" data-mage-init='{"amQty":{}}'>
                    <label class="amtheme-label-small" for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty">
                        <?= $escaper->escapeHtml(__('Qty')) ?>
                    </label>
                    <div class="control amtheme-qty-box">
                        <div class="amtheme-minus" data-amtheme-js="qty-minus" tabindex="0" title="Minus">
                            <svg class="amtheme-icon">
                                <use xlink:href="#icon-minus"></use>
                            </svg>
                        </div>
                        <div class="amtheme-plus" data-amtheme-js="qty-plus" tabindex="0" title="Plus">
                            <svg class="amtheme-icon">
                                <use xlink:href="#icon-plus"></use>
                            </svg>
                        </div>
                        <input type="number"
                               class="input-text qty amtheme-qty"
                               data-amtheme-js="qty-input"
                               tabindex="0"
                               id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                               name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $escaper->escapeHtmlAttr($item->getSku()) ?>"
                               value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                               size="4"
                               step="any"
                               title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"
                        />
                    </div>
                </div>
            </div>
        </td>
        <td class="col subtotal amtheme-column-toolbar">
            <div class="amtheme-cell">
                <div class="subtotal">
                    <span class="amtheme-label-small"><?= $escaper->escapeHtml(__('Subtotal')) ?></span>
                    <?php if ($canApplyMsrp): ?>
                        <span class="cart msrp subtotal">--</span>
                    <?php else: ?>
                        <?= $block->getRowTotalHtml($item) ?>
                    <?php endif; ?>
                </div>
            </div>
        </td>
    </tr>
    <tr class="item-actions">
        <td class="col item" colspan="4">
            <div class="actions-toolbar">
                <?php if($isBuildYourOwn): ?>
                    <input type="hidden" class="edit_cart_redirect_url" value="<?= $APP_BUILDER_URL .'/'.$product['sku'].'?q='.$maskedId.'&id='.$item->getItemId(); ?>"/>
                    <input type="hidden" class="prev-img-path" value="<?= $previewImgPath ?>"/>

                <?php endif;?>
                <button type="submit" style="border-radius: 0;" name="update_cart_action" data-cart-item-update="" value="update_qty" title="Update Shopping Cart" aria-label="Update Shopping Cart" class="action button-as-link update">UPDATE </button>
                <?= /* @noEscape */ $block->getActions($item) ?>
            </div>
        </td>
    </tr>
</tbody>
