<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('CUSTOMIZE NOW'); ?>

<?php if ($_product->isSaleable()):?>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span class="amtheme-title">
                        <?= $escaper->escapeHtml($buttonTitle) ?>
                    </span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

